#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#=============
#//CHANGELOG//
#=============
#20200510 - Created to sync files between vault and x1
#           It will copy files from vault to x1 without deleting anything, then transfer x1 files to vault
#20200514 - Made critical changes to rsync to exclude files
#
echo "----------------------"
echo "--[ Mounting Vault ]--"
echo "----------------------"
#Mount n1 vault
sudo mount -t cifs //192.168.1.111/n1 /mnt/tmp -o credentials=/home/nn/Keys/.vaultpassword
echo "---------------------------------------------------"
echo "--[ Do you want to check using a Dry-Run? (y/n) ]--"
echo "---------------------------------------------------"
read -p ""
echo
if [[ $REPLY =~ ^[Yy]$ ]]
  then
  #Dry-Run
  echo "------------------------------------------------------------------"
  echo "--[ DRY-RUN Syncing Documents and Linux files from Vault to x1 ]--"
  echo "------------------------------------------------------------------"
  #Sync Documents and Linux files from Vault to x1 without deleting x1 files
  rsync -avnh --progress --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /mnt/tmp/Files/Documents/ /home/nn/Documents/
  rsync -avnh --progress --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" --exclude={'Debian/Archive','Arch/Archive'} /mnt/tmp/Files/ComputerFiles/Linux/ /home/nn/Linux/
  echo "-----------------------------------------------------------------"
  echo "--[ DRY-RUN Backup Documents and Linux files from x1 to Vault ]--"
  echo "-----------------------------------------------------------------"
  #Backup Documents and Linux files from x1 to Vault
  sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /home/nn/Documents/ /mnt/tmp/Files/Documents/
  sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /home/nn/Linux/ --exclude={'Debian/Archive','Arch/Archive'} /mnt/tmp/Files/ComputerFiles/Linux/
fi
echo "----------------------------------"
echo "--[ Run Sync and Backup? (y/n) ]--"
echo "----------------------------------"
read -p ""
echo
if [[ $REPLY =~ ^[Yy]$ ]]
  then
  #Create backup_tmp.log and backup_page.log
  echo -n > /home/nn/logs/backup_tmp.log
  echo -n > /home/nn/logs/backup_page.log
  #Write initial header
  sh -c 'echo "     ////     //  ////     //" >> /home/nn/logs/backup_page.log'
  sh -c 'echo "    // //    //  // //    //" >> /home/nn/logs/backup_page.log'
  sh -c 'echo "   //  //   //  //  //   //" >> /home/nn/logs/backup_page.log'
  sh -c 'echo "  //   //  //  //   //  //" >> /home/nn/logs/backup_page.log'
  sh -c 'echo " //    // //  //    // //" >> /home/nn/logs/backup_page.log'
  sh -c 'echo "//     ////  //     ////" >> /home/nn/logs/backup_page.log'
  sh -c 'echo " " >> /home/nn/logs/backup_page.log'
  sh -c 'echo "x1 Carbon syncfiles script ran on `date`\n" >> /home/nn/logs/backup_page.log'
  sh -c 'echo " " >> /home/nn/logs/backup_page.log'
  echo "--------------------------"
  echo "--[ Backing up Keepass ]--"
  echo "--------------------------"
  cp -r /home/nn/Keys/ /home/nn/Documents/Keepass/Key/key_"$(date +%Y-%m-%d_%H%M%S)"/
  cp -r /home/nn/Dropbox/Key/ /home/nn/Documents/Keepass/Database/database_"$(date +%Y-%m-%d_%H%M%S)"/
  echo "-------------------------"
  echo "--[ Backing up Resume ]--"
  echo "-------------------------"
  cp -r /home/nn/Dropbox/Resume/ /home/nn/Documents/Resume/resume_"$(date +%Y-%m-%d_%H%M%S)"/
  echo "----------------------------------------------------------"
  echo "--[ Syncing Documents and Linux files from Vault to x1 ]--"
  echo "----------------------------------------------------------"
  sh -c 'echo "----------------------------------------------------------" >> /home/nn/logs/backup_page.log'
  sh -c 'echo "--[ Syncing Documents and Linux files from Vault to x1 ]--" >> /home/nn/logs/backup_page.log'
  sh -c 'echo "----------------------------------------------------------" >> /home/nn/logs/backup_page.log'
  #Sync Documents and Linux files from Vault to x1 without deleting x1 files
  sh -c 'echo "--[ /home/nn/Documents/ ]--" >> /home/nn/logs/backup_page.log'
  rsync -avh --progress --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /mnt/tmp/Files/Documents/ /home/nn/Documents/ --log-file=/home/nn/logs/backup_tmp.log
  tail -n 15 /home/nn/logs/backup_tmp.log | tee -a /home/nn/logs/backup_page.log
  sh -c 'echo "--[ /home/nn/Linux/ ]--" >> /home/nn/logs/backup_page.log'
  rsync -avh --progress --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" --exclude={'Debian/Archive','Arch/Archive'} /mnt/tmp/Files/ComputerFiles/Linux/ /home/nn/Linux/ --log-file=/home/nn/logs/backup_tmp.log
  tail -n 15 /home/nn/logs/backup_tmp.log | tee -a /home/nn/logs/backup_page.log
  echo "---------------------------------------------------------"
  echo "--[ Backup Documents and Linux files from x1 to Vault ]--"
  echo "---------------------------------------------------------"
  sh -c 'echo "---------------------------------------------------------" >> /home/nn/logs/backup_page.log'
  sh -c 'echo "--[ Backup Documents and Linux files from x1 to Vault ]--" >> /home/nn/logs/backup_page.log'
  sh -c 'echo "---------------------------------------------------------" >> /home/nn/logs/backup_page.log'
  #Backup Documents and Linux files from x1 to Vault
  sh -c 'echo "--[ /mnt/tmp/Files/Documents/ ]--" >> /home/nn/logs/backup_page.log'
  sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /home/nn/Documents/ /mnt/tmp/Files/Documents/ --log-file=/home/nn/logs/backup_tmp.log
  tail -n 15 /home/nn/logs/backup_tmp.log | tee -a /home/nn/logs/backup_page.log
  sh -c 'echo "--[ /mnt/tmp/Files/ComputerFiles/Linux/ ]--" >> /home/nn/logs/backup_page.log'
  sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /home/nn/Linux/ --exclude={'Debian/Archive','Arch/Archive'} /mnt/tmp/Files/ComputerFiles/Linux/ --log-file=/home/nn/logs/backup_tmp.log
  tail -n 15 /home/nn/logs/backup_tmp.log | tee -a /home/nn/logs/backup_page.log
  #Copy backup_page with date stamp for archive on x1
  cp /home/nn/logs/backup_page.log /home/nn/logs/sync_"$(date +%Y-%m-%d_%H%M%S)".log
  #Copy backup_page to NNBackup logging folder
  sudo cp /home/nn/logs/backup_page.log /mnt/tmp/Files/NNServer/x1.carbon/logs/sync_"$(date +%Y-%m-%d_%H%M%S)".log
  #delete temp files
  rm /home/nn/logs/backup_tmp.log
  rm /home/nn/logs/backup_page.log
fi
#unmount n1 vault
sudo umount -t cifs //192.168.1.111/n1