#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#=============
#//CHANGELOG//
#=============
#20200510 - Created to sync files between vault and x1
#           It will copy files from vault to x1 without deleting anything, then transfer x1 files to vault
#20200514 - Made critical changes to rsync to exclude files
#
echo "----------------------"
echo "--[ Mounting Vault ]--"
echo "----------------------"
#Mount n1 vault
sudo mount -t cifs //192.168.1.111/n1 /mnt/tmp -o credentials=/home/nn/Keys/.vaultpassword
echo "---------------------------------------------------"
echo "--[ Do you want to check using a Dry-Run? (y/n) ]--"
echo "---------------------------------------------------"
read -p ""
echo
if [[ $REPLY =~ ^[Yy]$ ]]
  then
  #Dry-Run
  echo "------------------------------------------------------------------"
  echo "--[ DRY-RUN Syncing Documents and Linux files from Vault to x1 ]--"
  echo "------------------------------------------------------------------"
  #Sync Documents and Linux files from Vault to x1 without deleting x1 files
  rsync -avnh --progress --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /mnt/tmp/Files/Documents/ /home/nn/Documents/
  rsync -avnh --progress --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" --exclude={'Debian/Archive','Arch/Archive'} /mnt/tmp/Files/ComputerFiles/Linux/ /home/nn/Linux/
  echo "-----------------------------------------------------------------"
  echo "--[ DRY-RUN Backup Documents and Linux files from x1 to Vault ]--"
  echo "-----------------------------------------------------------------"
  #Backup Documents and Linux files from x1 to Vault
  sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /home/nn/Documents/ /mnt/tmp/Files/Documents/
  sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /home/nn/Linux/ --exclude={'Debian/Archive','Arch/Archive'} /mnt/tmp/Files/ComputerFiles/Linux/
fi
echo "----------------------------------"
echo "--[ Run Sync and Backup? (y/n) ]--"
echo "----------------------------------"
read -p ""
echo
if [[ $REPLY =~ ^[Yy]$ ]]
  then
  echo "--------------------------"
  echo "--[ Backing up Keepass ]--"
  echo "--------------------------"
  cp -r /home/nn/Keys/ /home/nn/Documents/Keepass/Key/key_"$(date +%Y-%m-%d_%H%M%S)"/
  cp -r /home/nn/Dropbox/Key/ /home/nn/Documents/Keepass/Database/database_"$(date +%Y-%m-%d_%H%M%S)"/
  echo "-------------------------"
  echo "--[ Backing up Resume ]--"
  echo "-------------------------"
  cp -r /home/nn/Dropbox/Resume/ /home/nn/Documents/Resume/resume_"$(date +%Y-%m-%d_%H%M%S)"/
  echo "----------------------------------------------------------"
  echo "--[ Syncing Documents and Linux files from Vault to x1 ]--"
  echo "----------------------------------------------------------"
  #Sync Documents and Linux files from Vault to x1 without deleting x1 files
  rsync -avh --progress --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /mnt/tmp/Files/Documents/ /home/nn/Documents/
  rsync -avh --progress --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" --exclude={'Debian/Archive','Arch/Archive'} /mnt/tmp/Files/ComputerFiles/Linux/ /home/nn/Linux/
  echo "---------------------------------------------------------"
  echo "--[ Backup Documents and Linux files from x1 to Vault ]--"
  echo "---------------------------------------------------------"
  #Backup Documents and Linux files from x1 to Vault
  sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /home/nn/Documents/ /mnt/tmp/Files/Documents/
  sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /home/nn/Linux/ --exclude={'Debian/Archive','Arch/Archive'} /mnt/tmp/Files/ComputerFiles/Linux/
fi
#unmount n1 vault
sudo umount -t cifs //192.168.1.111/n1