#!/bin/bash
#   _  ___  __                         
#  / |/ / |/ /
# /    /    /   
#/_/|_/_/|_/  
#=============
#//CHANGELOG//
#=============
#v0.1 - 20200320 - Initial maintenance script created
#                - Used Arch wiki as base - https://wiki.archlinux.org/index.php/System_maintenance
#v0.2 - 20200323 - First script for updating Arch
#v1.0 - 20200402 - Combined update and maintenance scripts
#v1.1 - 20200706 - Refreshed look
#
echo "   _  ___  __ "
echo "  / |/ / |/ / "
echo " /    /    /  "
echo "/_/|_/_/|_/   "
echo "---------------------"
echo "--[ Updating Arch ]--"
echo "---------------------"
sudo pacman -Syu
echo "-------------------------"
echo "--[ Updating Arch AUR ]--"
echo "-------------------------"
yay -Syu --aur
echo "----------------------------------------"
echo "--[ Clean unused dependencies? (y/n) ]--"
echo "----------------------------------------"
read -p ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
  yay -Yc
fi
echo "-------------------------"
echo "--[ Check Logs? (y/n) ]--"
echo "-------------------------"
read -p ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "-------------------------------"
  echo "--[ SMART data on NVME disk ]--"
  echo "-------------------------------"
  sudo smartctl -a /dev/nvme0n1p1
  echo "-------------------------"
  echo "--[ TLP battery stats ]--"
  echo "-------------------------"
  sudo tlp-stat -b
  echo "--------------------------------"
  echo "--[ Updating locate database ]--"
  echo "--------------------------------"
  sudo updatedb
  echo "-----------------------------------------------------------------"
  echo "--[ Check if any systemd services have entered a failed state ]--"
  echo "-----------------------------------------------------------------"
  sudo systemctl --failed
fi
